// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/rogerogers/dingtalk-ops/internal/biz"
	"github.com/rogerogers/dingtalk-ops/internal/conf"
	"github.com/rogerogers/dingtalk-ops/internal/data"
	"github.com/rogerogers/dingtalk-ops/internal/server"
	"github.com/rogerogers/dingtalk-ops/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, dingtalk *conf.Dingtalk, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, dingtalk, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase)
	dingtalkRepo := data.NewDingtalkRepo(dataData, logger)
	dingtalkUseCase := biz.NewDingtalkUseCase(dingtalkRepo, logger)
	dingtalkService := service.NewDingtalkService(dingtalkUseCase)
	httpServer := server.NewHTTPServer(confServer, greeterService, dingtalkService, logger)
	grpcServer := server.NewGRPCServer(confServer, greeterService, dingtalkService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
